### ISSUE TITLE
('angular.json') could not be found

### ISSUE THREAD

**Issue by FIKUS0FIN** [mathieubruguier/angular-server-side-rendering-serverless#1]
## Steps 
npm i
npm run build:ssr

> Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/workspace-loader.js:31:21)
    at BuildCommand._loadWorkspaceAndArchitect (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/architect-command.js:201:32)
    at BuildCommand.<anonymous> (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/architect-command.js:53:25)
    at Generator.next (<anonymous>)
    at /Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/architect-command.js:3:12)
    at BuildCommand.initialize (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/architect-command.js:52:16)
    at Object.<anonymous> (/Users/lux/GA/ssr-lam/angular-server-side-rendering-serverless/node_modules/@angular/cli/models/command-runner.js:127:23)

**Comment by mathieubruguier** [comment]
Are you using Angular 6?

The file `angular.json` is used by Angular 6, while `angular.cli.json` (included in this repo) is used by Angular 5.
This repo was made before Angular 6 was a thing, and it's safe to say it won't work with it.

I would either suggest sticking to Angular 5 or using a [migration tool ](https://update.angular.io/) to update to Angular 6.

**Comment by FIKUS0FIN** [comment]
Thanks it helps )
